sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_install:
- npm i -g npm@5
- npm install grunt-cli -g
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q -O - http://opensource.wandisco.com/wandisco-debian.gpg | sudo apt-key add -
- sudo sh -c 'echo "deb http://opensource.wandisco.com/debian/ wheezy svn17" > /etc/apt/sources.list.d/wandisco-subversion.list'
- sudo apt-get -qq update
- sudo apt-get install -y --allow-downgrades subversion=1.7.22-1+WANdisco libsvn1=1.7.22-1+WANdisco
- svn --version
script:
- env
- npm run updateProject
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - node_modules
env:
  global:
  - TEAM_SERVER_URL=https://teamserver.sprintr.com
  - BRANCH_NAME=trunk
  - PROJECT_ID=d424a4fd-9473-4b53-94a5-99ad227c2278
  - MX_USER=as@flockfobirds.org
  - secure: cdaAW2R1f6xxiZQ+vsiiI86MOLs8mBCaY+wd4S70ZxHw1cXnFcS1W1aXYTE9TF92tR8aNktMPPqphcGz4xZc5YS0p53vyOUdryUzr9QAW38AvHXRBRcj3x+EfvDcbdOyhmCVfhpuBTIXvaTkHScN8VZfJ6ve+OztNJgXYLqgg2Byg2AQjeTatyfg4sTCZ23htnl9xgGX51RmUaPKwvWvOBtOTzpWnm6GB/bwbmbFzP75+3HvSTOgGjafBmTi2j70twJGPm3q7gskXcQeheKqUcYLx+z5F2J8cLhrIm1YA0RYDP4KcYahmnBj3UeaeA+oK8bvbtGuWJZO7qGc+tOGMGTQtotHNT25OlV+3RXsHg4WNXPvPZXYFBI2uHVt3MoavHvf4lc6ckDGgosQdcWUf6N6MurlG6FSySYB9nKPZNp6pDjQlyNv8pgzCYsLvaHYGcTgQjrP+aruYIAdSacYjkHeq/HWrXXJ2F4pRAkpAvC0nig7FVgeZBnCmrLQgVTLiaGyaFVYblWahojFkecovmwSG6HBZiSifuCSXXccHHbafyu/feKNVjt7fp/d3s1HJ5KfJt3Y81E1ksXlEFAm7pimdewy5+w7y/kFHzU9VYjfr3nncQmBID9p7jcWazVGbIJS6g6giLiDO2Sf6IDuz8oFb8PfDKGer5m+X9i6RL4=
