sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_install:
- npm i -g npm@5
- npm install grunt-cli -g
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q -O - http://opensource.wandisco.com/wandisco-debian.gpg | sudo apt-key add
  -
- sudo sh -c 'echo "deb http://opensource.wandisco.com/debian/ wheezy svn17" > /etc/apt/sources.list.d/wandisco-subversion.list'
- sudo apt-get -qq update
- sudo apt-get install -y --allow-downgrades subversion=1.7.22-1+WANdisco libsvn1=1.7.22-1+WANdisco
- svn --version
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - node_modules
env:
  global:
  - MX_API_URL=https://deploy.mendix.com/api/1
  - MX_APP_NAME=texteditorwidget
  - MX_TEAM_SERVER_URL=https://teamserver.sprintr.com
  - MX_BRANCH_NAME=trunk
  - secure: ZAFagdWRAiDPp+lGH2rra4Hz4y0jV8TkBvWpj7fahC8l3t5YDH89mxtJUDNF6lV+GUB4o08lSWsnKHCP4Qj3A/n5mws27csvZQF//0mP5rXGEGQg/esDUwSJCYNc3NKG0OZsHi8X3AVF5ysCJBULKgr8C1P8GfPSDY4oEaIkLs38/FKRkMnvyTQl4cyybEKi3nDS/BCXJuh4XiRAJGQ2QdF6karZkWPBjTYne2hh0H95+b0NEgg/5JC6r4fFPuIpZPaavyaCc5teYCBdeqQ5l+8iQ+Qcc6FEq3hd6VaEdPslzMefeBHU3NL50j42IDxMbSVPtMGtpWEgNMX546zaARVBwz7ai3oabtg5IacBnT2IuCtZ1NeCWTyceBX164M1sKm5DW88duN2FHgrxVIvUEH4NzuhdGXlxDsaTP1RUGTB/sPl/onZeXXLhah228r/Iijn4g+MiPairgdY/wq0mgUXfYHcI1EP6KU8IQH2drDetxV0DiDjQFB7M5wimvipQbfYEsTVa3uNYpmfSTgOAXewYwL5dlw8va9zBseX1ykuTqp197P4c0J8Oq/ooz0TU+CdQhGT7VUzATFYYQUyGqNgx7VsX8GNONeLkX7ywpsKNciUSQWWvUQ1b7AL1otqs+UqzwzeAe4pwOi30fNzlDLp7v9opbonDXADY1INOjs=
  - MX_ENVIRONMENT=Sandbox
  - MX_PROJECT_ID=8648ccda-9281-4768-abb2-8ce61a80e2f1
  - MX_USER=ci@flockofbirds.nl
  - secure: fzIxF5ER2BZ55xcGTzLML9vAp0t7sVIIDrvJaTcX1VOkPk6pWwWzFQFT5o/8cN9W/XEQfWWkbyfL1rp9+WsE9DgGA7NK3lfSIhC87cxHT9mig9EO5zCOX9Chtxe+wIvfN/dAGFhvr3SOBr5JMn3BvwPGJXdpStK4+ehZjbBaX73odQdT3aa4MYUc9tH3JFMpcORU2WlpqfJogn03BcXM1Qkxh6gNEB+1Q7XraNIrJUsybw8NDrmZejYLCIJYSAWTXfK8tD3QUZDFqOB0j2MVSr1RBy9FXA6TYgYamRPJmzPp65rC94x30KqbOnRbD97SKnSZ887lGnA0s+dhrOqcGTXpdvPAb4YY7QUHEyNRy68CXBv8F4yxl/BTBG5MgHLHUoHWvUu5nJ0axh9SPIeloglpckEEUCoo9ZW5QBcLtKHgi0GN0wPjKS7n+EDq94ZoA2j+V+lhD7uwgnRvIrFVVqEacJPxB7yI+EX0mUkiuVr0+fus20u+JCQ96eCSfZLZhLRKMSx+Jiqk/lRjlgMKwY0vPP8827FySby72nxg8jaMNbCC6/uTG77l81cshoejCPygahiRQ261dUswDr0/XDoihss2vp4NUKWGswGjo9HRQ2RyIC/gwUIUsKL4lIW2Of9utQA/T2bsZWlnhL3TrxTtM4uCD9ypWSZcOWVafIM=
deploy:
  provider: releases
  api_key:
    secure: mQtgwYHfLN8JGuTUQfKrBxJsGw5oG9ii0qa8gBDQL5uz2XHxj7BYzuUfbu9P0emWp4vWImLaIp398GM1EicoBvCSSlJrfW6KnlNz+VT3c93wm1SVf+Vjk6Pm5Qjnyk43R11L0xhSumxPk+BWycdQ0yaNmmjRLriVbEz2d9JnHMcdYBRXcIC0HrKFgS8KEiuPzxaHcqALOVzczGuVe3sCHhDZ0pmlpQlu+zzBLjN18UbS2H3lx7wGg5pcKzKuuo2DxxZdLiMGCbh3bfBaWwCBHZ3nDESSj4UbZyhPmVCYijNRLauYQJgg2wDO3g5lD3UNIZ5Hx7zMUX1h0b+DPCaAX7wsuxgHTF243Nx+Qcp5R/FEKqNHYRqYFnhHfvx+ABEaZEt5xAqlSV44LhQuW+DAA/X/3+/BZSOx7lO+yLkEWDkKaOwzLcLMue0eBw2TZqciXvrypzz3JVcx/d0VeSbSnmmAT7eTRxdbxuFxCMc+tPw59kL+hbG7Rq4I/wWjtoi4AuEALn++au4Wm5zIkQmpMoCFNJ9UwWHas4SCDh140sGMYj8DJC7YghWW2SnHoOhFzpgMtOvoptpN2c5rjFBhOt3rIlsIE1TjlPztihSH69rd2cm3FgM7iljjdd3E6XwrXC5mTMWpcOfTrk4aR8xJnIqQNmPmUusG5q9ZnxBcmRw=
  file_glob: true
  file: dist/release/*
  skip_cleanup: true
  on:
    repo: Andries-Smit/rich-text
    tags: true
