sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_install:
- npm i -g npm@5
- npm install grunt-cli -g
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q -O - http://opensource.wandisco.com/wandisco-debian.gpg | sudo apt-key add -
- sudo sh -c 'echo "deb http://opensource.wandisco.com/debian/ wheezy svn17" > /etc/apt/sources.list.d/wandisco-subversion.list'
- sudo apt-get -qq update
- sudo apt-get install -y --allow-downgrades subversion=1.7.22-1+WANdisco libsvn1=1.7.22-1+WANdisco
- svn --version
script:
- npm run updateProject
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - node_modules
env:
  global:
  - TEAM_SERVER_URL=https://teamserver.sprintr.com
  - BRANCH_NAME=trunk
  - PROJECT_ID=d424a4fd-9473-4b53-94a5-99ad227c2278
  - MX_USER=as@flockfobirds.org
  - secure: djddOI0A0XEkXIGrsWgFfOockfymVfJ3eQ53kLRSuoqkXyQ+ZIGBPVy5lQZxS415eI6dkP8x8Fo/EQX4lIFm1g0z5GsjHPrXWiIeALBi/1kHxu8rFfGu94uzt0Qc7Xj90zILEPZGXVVGN3HMr7AgaG+tDL2PJTvRHgzhFl9n3/906K9M2+QYu6M02t4EsOdcfkv4nwjE4cNw48YGLaSGqxHp+rjSuCi9TXsvKN6ubaNkYaLdF6n4KeN6usftp5KG2TsBQEVvjRAROhxhdRn1pH9R7SS4Z3Is8B/GzWjDFF4G+m/brnT5+t2cGOTdj5N1yv6MQiZ8rtj3tRfMbej/z0XX1ashfSD2fn/rmTN4S/bHVgNYHyVZEZu3YhroJlE2ZTuTztbYZPp8yhpYozF9nXATcvfymEy9Cryav8JWIEw3pNfU9HLWN6/Ov/SCjJ+M5wuyclMkjFD4yBt7uXAB86B3D6MLHBQPS66yrW15Tan/6ynDN5ctKvHCevJxWasERn9BoNQveA1hvKprXFJKS0EGsTVcSC55B9vTX75Unbhsi4wOwg6ZcG4v8TeryRK9D0QTA35cDkUqTxFSrZBnkHBuMy5RTkQDpqkakT8VfP6wRqbIZBkppls6CuhR0UO7s8p3pfnw/zfTFcLzlHjsXoHSnPwPJRzlRO9+/8i8MCQ=
