sudo: required
dist: trusty
language: node_js
node_js:
  - '4.2'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - npm i -g npm@5
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - "node_modules"
